<!DOCTYPE html>
<html lang="de">
<head>
    <title>HARDKODE | <?= $this->renderBlock('title', 'Tutorials, Tools und mehr..') ?></title>
    <?= $this->assetList('css') ?>
    <link href="https://fonts.googleapis.com/css2?family=Economica:wght@400;700;900&family=Marvel&family=Palanquin&family=Share+Tech+Mono&display=swap" rel="stylesheet">
</head>
<body>

    <header>
        <a class="logo-container" href="/">
            <div id="logo">
                <span>HARD<strong>KODE</strong></span>
            </div>
        </a>
        <div id="navigation">
            <?= $this->link('admin:articles') ?>
            <?= $this->link('admin:tools') ?>

            <?php if ($this->session()->get('userId') && $this->user()->hasRole('admin')): ?>
                <?= $this->link('admin:dashboard', [], $this->user()->getUsername()) ?>
            <?php elseif ($this->session()->get('userId') && $this->user()->hasRole('registered')): ?>
                <?= $this->link('profile', [], $this->user()->getUsername()) ?>
            <?php else: ?>
                <?= $this->link('login') ?>
            <?php endif; ?>
        </div>
    </header>

    <div id="app">
        <?= $this->renderBlock('content') ?>
    </div>

    <?= $this->assetList('js') ?>

</body>
</html>
