<!DOCTYPE html>
<html lang="de">
<head>
    <title>HARDKODE | <?= $this->renderBlock('title', 'Tutorials, Tools und mehr..') ?></title>
    <?= $this->assetList('css') ?>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,400;0,700;1,400;1,700&family=Economica:wght@400;700&display=swap" rel="stylesheet" />
</head>
<body>

    <header>
        <div id="logo"><a href="/"><span>&lt;/&gt;</span>  hardkode</a></div>
        <div id="menu">
            <?= $this->link('tutorials') ?>
            <?= $this->link('downloads') ?>

            <?php if ($this->session()->get('userId') && $this->user()->hasRole('admin')): ?>
                <?= $this->link('admin:dashboard', [], $this->user()->getUsername()) ?>
            <?php elseif ($this->session()->get('userId') && $this->user()->hasRole('registered')): ?>
                <?= $this->link('profile', [], $this->user()->getUsername()) ?>
            <?php else: ?>
                <?= $this->link('login') ?>
            <?php endif; ?>
        </div>
    </header>

    <div id="app">

        <?= $this->renderBlock('content') ?>

        <footer>
            <?= $this->link('impress') ?>
            <?= $this->link('contact') ?>
        </footer>

    </div>

    <?= $this->assetList('js') ?>
    <script src="/js/highlight.pack.js"></script>

</body>
</html>
