<?php
/**
 * @var \Hardkode\Form\Login $form
 */
?>
<?php $this->layout('/layout.phtml') ?>

<?php $this->block('content') ?>

<div class="container spaced">

    <div id="login">

        <h2>Login</h2>

        <hr />

        <?= $form->open() ?>

            <?= $this->showMessage('form.error') ?>
            <?= $form->getField('csrf')->getErrorMessages() ?>
            <div class="grid vertical">
                <div class="width-100">
                    <?= $form->getField('username') ?>
                </div>
                <div class="width-100">
                    <?= $form->getField('password') ?>
                </div>
            </div>

            <hr />

            <?= $form->getField('button') ?>

        <?= $form->close() ?>

    </div>


</div>

<?php $this->endBlock('content') ?>
