<?php
/**
 * @var \Hardkode\Form\Login $form
 */
?>
<?php $this->layout('/layout.phtml') ?>

<?php $this->block('content') ?>

<div class="container spaced">

    <h1>Login</h1>

    <?= $form->open() ?>

        <?= $this->showMessage('form.error') ?>

        <?= $form->getField('username') ?>
        <?= $form->getField('username')->getErrorMessages() ?>

        <?= $form->getField('password') ?>
        <?= $form->getField('password')->getErrorMessages() ?>

        <?= $form->getField('button') ?>

        <?= $form->getField('csrf')->getErrorMessages() ?>

    <?= $form->close() ?>

</div>

<?php $this->endBlock('content') ?>
