<?php
/**
 * @var Hardkode\Model\Article[] $articleList
 */
?>
<?php $this->layout('/layout.phtml') ?>

<?php $this->block('title') ?>
Startseite
<?php $this->endBlock('title') ?>

<?php $this->block('content') ?>

<div class="container spaced">
    <h1>Herzlich Willkommen!</h1>
</div>

<div class="container spaced">
    <div class="personal-profile grid">
        <div class="personal-image round"></div>
        <div>
            Nun hast Du es wirklich auf meine Seite geschafft.<br />
            <strong>Servus!</strong> I bims, der Flo.
        </div>
    </div>

    <h2>Neueste Einträge</h2>

    <?php

    /** @var \Hardkode\Model\Article $article */
    foreach ($articleList as $article) {
        echo $article->getTitle() . '<br />';
    }

    ?>

</div>

<?php $this->endBlock('content') ?>
