<?php $this->layout('/layout.phtml') ?>

<?php $this->block('title') ?>
Startseite
<?php $this->endBlock('title') ?>

<?php $this->block('content') ?>

<div class="container spaced">
    <h1>Herzlich Willkommen!</h1>
</div>

<div class="container spaced">
    <div class="grid personal-profile">
        <div class="personal-image round"></div>
        <div>
            Nun hast Du es wirklich auf meine Seite geschafft.<br />
            Servus! I bims, der Flo.
        </div>
    </div>
</div>

<?php $this->endBlock('content') ?>
