<?php
/**
 * @var Hardkode\Model\Article[] $articleList
 */
?>
<?php $this->layout('/layout.phtml') ?>

<?php $this->block('title') ?>
Startseite
<?php $this->endBlock('title') ?>

<?php $this->block('content') ?>

<div class="stage">

    <div class="text">
        <div class="date">25.06.2020 // 18:06 Uhr</div>
        <h1>Animationen mit CSS</h1>
    </div>

</div>

<div class="grid">

    <div class="box">
        <div class="date">25.06.2020 // 18:06 Uhr</div>
        <h3>Das Docker-Image erklärt</h3>
    </div>

    <div class="box">
        <div class="date">25.06.2020 // 18:06 Uhr</div>
        <h3>Wie verknüpfe ich AWS-Konten?</h3>
    </div>

    <div class="box">
        <div class="date">25.06.2020 // 18:06 Uhr</div>
        <h3>MySQL mit Docker nutzen</h3>
    </div>

</div>

<!--

<div class="container spaced">
    <h1>Herzlich Willkommen!</h1>
</div>

<div class="container spaced">
    <div class="personal-profile grid">
        <div class="personal-image round"></div>
        <div>
            Nun hast Du es wirklich auf meine Seite geschafft.<br />
            <strong>Servus!</strong> I bims, der Flo.
        </div>
    </div>

    <h2>Neueste Einträge</h2>

    <?php /** @var \Hardkode\Model\Article $article */
    foreach ($articleList as $article): ?>

        <div class="box link" data-href="/article/<?= $article->id ?>">
            <span class="font-small">
                <?= $this->date($article->insertedAt)->format('d.m.Y - H:i') . ' Uhr' ?>
            </span>
            <span><?= $article->title ?></span>
        </div>


    <?php endforeach; ?>

</div>

-->

<?php $this->endBlock('content') ?>
